import { ItemFields } from "./mock-item-fields" 

export const mockData: ItemFields[] = [
    { id: 1,
    name: "Adaptive Tray",
    category: "Fair",
    description: "Missing a piece",
    size: "Medium",
    status: "Available",
    donor: "Stacy M.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/9/2026" }, 

    { id: 2,
    name: "Posterior Walker",
    category: "Good",
    size: "Medium",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 3,
    name: "Item 3",
    category: "OK",
    size: "Large",
    status: "In Processing",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 4,
    name: "Item 4",
    category: "Excellent",
    size: "Small",
    status: "Permanently Allocated",
    donor: "Ashley S.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 5,
    name: "Item 5",
    category: "Good",
    size: "Medium",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 6,
    name: "Item 6",
    category: "OK",
    size: "XL",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 7,
    name: "Item 7",
    category: "Good",
    size: "Medium",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 8,
    name: "Item 8",
    category: "Good",
    size: "XS",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 0,
    name: "Item 9",
    category: "Excellent",
    size: "XS",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

]