import { ItemFields } from "./field_interfaces" 

export const mockData: ItemFields[] = [
    { id: "550e8400-e29b-41d4-a716-446655440000",
    name: "Adaptive Tray",
    category: "Adaptive Tray",
    condition: "Broken/Missing Pieces",
    description: "Missing a piece on underside",
    size: "Medium",
    color: "Yellow",
    status: "Available",
    donor: "Stacy M.",
    image_urls: ["/adaptive-tray.jpg", "/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/9/2026" }, 

    { id: "750e8300-e29b-42d4-a136-446656640000",
    name: "Blue Posterior Walker",
    category: "Walker",
    subcategory: "Posterior",
    condition: "Good",
    size: "Medium",
    color: "Blue",
    status: "Available",
    donor: "Ashley S.",
    image_urls: ["/posterior-walker.jpg", "/adaptive-tray.jpg", "/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: "178e9800-e39b-42d4-a136-886656640000",
    name: "Silver Manual Rigid Wheelchair",
    category: "Wheelchair",
    subcategory: "Manual Rigid",
    condition: "Excellent",
    size: "Large",
    color: "Green",
    status: "In Processing",
    donor: "Ashley S.",
    image_urls: ["/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: "650e4300-e21b-22d4-a137-446656640098",
    name: "Activity Chair",
    condition: "Needs Cleaning",
    category: "Activity Chair",
    size: "Small",
    color: "Yellow",
    status: "Allocated",
    donor: "Ashley S.",
    image_urls: ["/adaptive-tray.jpg", "/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: "750e3210-e29b-42d4-a136-446656221000",
    name: "Item 5",
    category: "Gait Trainer",
    condition: "Good",
    size: "Medium",
    color: "Red",
    status: "Available",
    donor: "Ashley S.",
    image_urls: ["/posterior-walker.jpg", "/adaptive-tray.jpg", "/posterior-walker.jpg", "/adaptive-tray.jpg" ],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: "960e8300-e29b-12d4-a176-876652140000",
    name: "Item 6",
    category: "Adaptive Tricycle",
    condition: "Broken/Missing Pieces",
    size: "XL",
    color: "Purple",
    status: "Available",
    donor: "Ashley S.",
    image_urls: ["/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: "841e8300-e29b-42d4-a136-446656646678",
    name: "Item 7",
    category: "Forearm Crutches",
    condition: "Good",
    size: "Medium",
    color: "Blue",
    status: "Available",
    donor: "Ashley S.",
    image_urls: ["/adaptive-tray.jpg"],
    qr_code_url: "To-do",
    created_at: "8/2/2026" }, 

    { id: "670e8310-e39b-47d4-a131-486696640000",
    name: "Item 8",
    category: "Wheelchair",
    subcategory: "Sport",
    condition: "Excellent",
    size: "XS",
    color: "Pink",
    status: "Available",
    donor: "Ashley S.",
    image_urls: ["/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: "236e9851-e49b-42d6-a962-541362540000",
    name: "Item 9",
    category: "Wheelchair",
    subcategory: "Manual Folding",
    condition: "Acceptable",
    description: 
        "Good for kids. This is a long description to check how it looks when the description length is longer. Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs  Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs Text text text text text afkljs",
    size: "XS",
    color: "Silver",
    status: "Available",
    donor: "Ashley S.",
    image_urls: ["/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: "852e8300-e96b-72d4-a136-446656641049",
    name: "Item 10",
    category: "Other",
    condition: "Excellent",
    description: "Really great item",
    size: "XS",
    color: "Green",
    status: "Reserved",
    donor: "Ashley S.",
    image_urls: ["/posterior-walker.jpg"],
    qr_code_url: "To-do",
    created_at: "9/10/2026" }

]